list: $/skippy/fms/models/postlist/columns.yaml
modelClass: Skippy\Fms\Models\Postlist
title: Postlist
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'skippy/fms/postlist/update/:id'
