list: $/skippy/fms/models/operations/columns.yaml
modelClass: Skippy\Fms\Models\Operations
title: Operations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'skippy/fms/operations/update/:id'
