title: Sims
modelClass: Skippy\Fms\Models\Sim
list: $/skippy/fms/models/sim/columns.yaml
recordUrl: 'skippy/fms/sims/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
