departments:
    label: Department
    tabs: Manifest
    manage:
        form:
            fields:
                dept_name:
                    label: 'Department Name'
                    span: auto
                    type: text
        list: $/skippy/fms/models/department/columns.yaml
        showSearch: true
        filter:
            scopes:
                genre_id:
                    label: Genre
                    modelClass: Skippy\Fms\Models\Genre
                    conditions: genre_id in (:filtered)
                    nameFrom: genre_name
    view:
        list: $/skippy/fms/models/department/columns.yaml
