list: $/skippy/fms/models/division/columns.yaml
modelClass: Skippy\Fms\Models\Division
title: Divisions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'skippy/fms/divisions/update/:id'
