list: $/skippy/fms/models/fleet/columns.yaml
modelClass: Skippy\Fms\Models\Fleet
title: Fleets
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'skippy/fms/fleets/update/:id'
